// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARLeaB7onXKL38zsnccxe78UM0KqaGAvs',
    appId: '1:605641003798:web:5162bc35eb445381337637',
    messagingSenderId: '605641003798',
    projectId: 'octohub-assignment',
    authDomain: 'octohub-assignment.firebaseapp.com',
    storageBucket: 'octohub-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNiJ_A_gREECEfqK4j858hoAB1Knvws8',
    appId: '1:605641003798:android:d541a8e0a18d7460337637',
    messagingSenderId: '605641003798',
    projectId: 'octohub-assignment',
    storageBucket: 'octohub-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9FC2qIKR5nIP0yttKkroPPdg83yT-LE',
    appId: '1:605641003798:ios:22900b9ba510368e337637',
    messagingSenderId: '605641003798',
    projectId: 'octohub-assignment',
    storageBucket: 'octohub-assignment.appspot.com',
    iosClientId: '605641003798-ce1b6b43ih8pam95stpp8vccbir76f4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.octohubAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9FC2qIKR5nIP0yttKkroPPdg83yT-LE',
    appId: '1:605641003798:ios:22900b9ba510368e337637',
    messagingSenderId: '605641003798',
    projectId: 'octohub-assignment',
    storageBucket: 'octohub-assignment.appspot.com',
    iosClientId: '605641003798-ce1b6b43ih8pam95stpp8vccbir76f4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.octohubAssignment',
  );
}
